ALTER TABLE monitors ADD COLUMN is_paused TINYINT(1) DEFAULT 0;
ALTER TABLE monitors ADD COLUMN emails_sent_this_hour INT DEFAULT 0;
ALTER TABLE monitors ADD COLUMN hour_start_time TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE monitors ADD COLUMN last_changed TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE monitors ADD COLUMN last_screenshot VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE monitors ADD COLUMN was_throttled TINYINT(1) DEFAULT 0;
